# GLOBAL SITE SETTINGS

cname: station95.yourwebvisual.com

# META
title: Station95
title_homepage: stationinetyfive - Hair | Beauty | Gifts - Adelaide, South Australia
company: Station95
description: Hair | Beauty | Gifts - Adelaide, South Australia

# SITE DEFAULTS
site_tagline:

# DEVELOPER
allow_robots: false
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/ninetyfive-0417
github_repo_name: ninetyfive-0417
jekyll_version: 3.0.3

# OFFICES
offices:
  - title: Walkerville
    address: 95 walkerville terrace walkerville sa 5081
    phone: 08 8269 3981
    email: hello@station95.com.au
    trading_hours: "<p>sun and mon closed<br> tues 9am, late night by appointment<br> wed 9am - 5.30pm | thurs 9am - 5.30pm <br>fri 9am - 5.30pm  | sat 9am - 4pm</p>"

# SOCIAL MEDIA
facebook:
linked_in:
google_plus:
instagram: http://instagram.com

# GOOGLE
google_analytics: "UA-XXXXXXXX-X"

# AUTHOR
author:
  title: Mitch
  url: http://liquidvisual.com
  logo: /assets/img/ui/liquidvisual-logo.svg
  description: liquidvisual